import type { Metadata } from "next";
import "./globals.css";
import { Aboreto, Jost } from "next/font/google";

const aboreto = Aboreto({ subsets: ["latin"], weight: "400" });
const jost = Jost({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Rachel's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body className={jost.className}>
          <main className={aboreto.className}>{children}</main>
        </body>
      </html>
    </>
  );
}
